### ISSUE TITLE
Inline code does not work

### ISSUE THREAD

**Issue by tractatus** [quarto-ext/typst-templates#3]
Code blocks work but inline code wont render:

```
There are `r nrow(mpg)` observations in our data. 
```

Renders to:

There are `r nrow(mpg)` observations in our data

**Comment by cderv** [comment]
Hi, 

What is the full content of your .qmd document ? Do you have other code chunk with R engine ? 
Did you try setting `engine: knitr` in the YAML ? 

If your document only contains some inline code chunk, you need to explicitly set the engine to use as automatic engine binding won't use **knitr**. 

You can learn more about automatic engine binding at https://quarto.org/docs/computations/execution-options.html#engine-binding 

Hope it helps

**Comment by tractatus** [comment]
Hi,

Wow. Thanks for the super quick response.
Yes setting `engine: knitr` does solve this.

Im closing this issue.
